services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
    ports:
      - "13001:3000"
    env_file:
      - .env.local
    environment:
      - NODE_ENV=development
    command: npm run dev
    restart: always
volumes:
  node_modules: 