services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - node_modules:/workspace/node_modules
    ports:
      - "13001:3000"
    environment:
      - NODE_ENV=development
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    command: npm run dev
    restart: always
volumes:
  node_modules: 